/*
 * Influx API Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// CheckStatusLevel The state to record if check matches a criteria.
type CheckStatusLevel string

// List of CheckStatusLevel
const (
	UNKNOWN CheckStatusLevel = "UNKNOWN"
	OK CheckStatusLevel = "OK"
	INFO CheckStatusLevel = "INFO"
	CRIT CheckStatusLevel = "CRIT"
	WARN CheckStatusLevel = "WARN"
)

func (v *CheckStatusLevel) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CheckStatusLevel(value)
	for _, existing := range []CheckStatusLevel{ "UNKNOWN", "OK", "INFO", "CRIT", "WARN",   } {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CheckStatusLevel", value)
}

// Ptr returns reference to CheckStatusLevel value
func (v CheckStatusLevel) Ptr() *CheckStatusLevel {
	return &v
}

type NullableCheckStatusLevel struct {
	value *CheckStatusLevel
	isSet bool
}

func (v NullableCheckStatusLevel) Get() *CheckStatusLevel {
	return v.value
}

func (v *NullableCheckStatusLevel) Set(val *CheckStatusLevel) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckStatusLevel) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckStatusLevel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckStatusLevel(val *CheckStatusLevel) *NullableCheckStatusLevel {
	return &NullableCheckStatusLevel{value: val, isSet: true}
}

func (v NullableCheckStatusLevel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckStatusLevel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

